import * as fs from 'fs';
import * as path from 'path';
import { HNSW } from '../src';
import { cosineSimilarity } from '../src/similarity';
import {
  asymmetricSimilarity,
  buildWithSeededLevels,
  FIXTURE_FILE,
  K,
  l1Similarity,
  makeCorpora,
  mulberry32,
} from './fixtures/corpus.helper';

// All fixtures in this file were generated by running the pre-cached-norm
// implementation (main @ 8542a17, three dot products per cosine call) over the
// exact corpora defined in fixtures/corpus.helper.ts. See
// fixtures/generate.test.ts for the generation procedure.

const legacyExpected: Record<string, { id: number; score: number }[][]> = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'searchResults.json'), 'utf8'),
);

const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', FIXTURE_FILE), 'utf8'));

// Fixtures travel through JSON, which cannot represent -0 (or NaN); normalize
// live results the same way before comparing. Signed zeros only arise from
// custom similarity functions returning -0.
const viaJSON = (value: unknown) => JSON.parse(JSON.stringify(value));

const dims = 16;
const rngVec = mulberry32(42);
const legacyData = Array.from({ length: 300 }, (_, i) => ({
  id: i,
  vector: Array.from({ length: dims }, () => rngVec() * 2 - 1),
}));
const legacyQueries = Array.from({ length: 10 }, () => Array.from({ length: dims }, () => rngVec() * 2 - 1));

describe('search results are unchanged by the cached-norm optimization', () => {
  it.each(['cosine', 'euclidean'] as const)('%s metric matches the pre-change fixture exactly', async (metric) => {
    const hnsw = new HNSW(16, 64, dims, metric, 64);
    await buildWithSeededLevels(hnsw, legacyData);
    const results = legacyQueries.map((q) => hnsw.searchKNN(q, 10));
    expect(results).toEqual(legacyExpected[metric]);
  });
});

describe('pre-change fixtures across dims, zero vectors, Float32Array inputs, and near-ties', () => {
  const corpora = makeCorpora();
  const cases: [string, string][] = [];
  for (const corpus of corpora) {
    for (const metric of ['cosine', 'euclidean']) {
      cases.push([corpus.name, metric]);
    }
  }

  it.each(cases)('%s %s: search results match exactly', async (name, metric) => {
    const corpus = corpora.find((c) => c.name === name)!;
    const hnsw = new HNSW(16, 64, corpus.dims, metric, 64);
    await buildWithSeededLevels(hnsw, corpus.data);
    const results = corpus.queries.map((q) => hnsw.searchKNN(q, K));
    expect(viaJSON(results)).toEqual(fixture.corpora[`${name}-${metric}`].searchResults);
  });

  it.each(cases)('%s %s: toJSON graph matches the pre-change graph exactly', async (name, metric) => {
    const corpus = corpora.find((c) => c.name === name)!;
    const hnsw = new HNSW(16, 64, corpus.dims, metric, 64);
    await buildWithSeededLevels(hnsw, corpus.data);
    expect(JSON.parse(JSON.stringify(hnsw.toJSON()))).toEqual(fixture.corpora[`${name}-${metric}`].graph);
  });

  it.each(cases)('%s %s: searching a pre-change serialized graph via fromJSON matches exactly', (name, metric) => {
    const corpus = corpora.find((c) => c.name === name)!;
    const restored = HNSW.fromJSON(fixture.corpora[`${name}-${metric}`].graph);
    const results = corpus.queries.map((q) => restored.searchKNN(q, K));
    expect(viaJSON(results)).toEqual(fixture.corpora[`${name}-${metric}`].restoredSearchResults);
  });
});

describe('public similarityFunction is respected', () => {
  it('a constant custom function replaces scoring entirely (one-node index)', async () => {
    const hnsw = new HNSW(16, 64, 3, 'cosine', 64);
    await hnsw.addPoint(0, [1, 2, 3]);
    hnsw.similarityFunction = () => 42;
    expect(hnsw.searchKNN([4, 5, 6], 1)).toEqual([{ id: 0, score: 42 }]);
  });

  it('an asymmetric function assigned after build gets pre-change operand orientation', async () => {
    const corpus = makeCorpora().find((c) => c.name === 'd16')!;
    const hnsw = new HNSW(16, 64, corpus.dims, 'cosine', 64);
    await buildWithSeededLevels(hnsw, corpus.data);
    hnsw.similarityFunction = asymmetricSimilarity;
    const results = corpus.queries.map((q) => hnsw.searchKNN(q, K));
    expect(viaJSON(results)).toEqual(fixture.customFn.postBuildAsymmetric);
    // Final scoring calls similarityFunction(node.vector, query), as pre-change.
    for (let qi = 0; qi < corpus.queries.length; qi++) {
      for (const { id, score } of results[qi]) {
        expect(score).toBe(hnsw.nodes.get(id)!.vector[0] - corpus.queries[qi][0]);
      }
    }
  });

  it('a custom function assigned before build shapes construction identically to pre-change', async () => {
    const corpus = makeCorpora().find((c) => c.name === 'd16')!;
    const hnsw = new HNSW(16, 64, corpus.dims, 'cosine', 64);
    hnsw.similarityFunction = l1Similarity;
    await buildWithSeededLevels(hnsw, corpus.data);
    const results = corpus.queries.map((q) => hnsw.searchKNN(q, K));
    expect(viaJSON(results)).toEqual(fixture.customFn.preBuildL1);
  });
});

// Contract: vectors are immutable once inserted. The index stores vectors by
// reference and caches each node's L2 norm at insert time, so mutating a
// vector afterwards produces stale-but-stable scores: the cached norm is the
// original vector's, while dot products read the mutated contents. This test
// pins that semantics so the contract is enforced by test, not just prose.
describe('immutability contract: mutation after insert yields stale-but-stable scores', () => {
  it('post-insert mutation does not produce fresh cosine scores', async () => {
    const data = Array.from({ length: 6 }, (_, i) => ({
      id: i,
      vector: [i + 1, i + 2, i + 3],
    }));
    const hnsw = new HNSW(16, 64, 3, 'cosine', 64);
    await buildWithSeededLevels(hnsw, data);
    const query = [0.5, -0.25, 1];

    const before = hnsw.searchKNN(query, 6).find((r) => r.id === 2)!;
    data[2].vector[0] = -50; // contract violation: mutate in place after insertion
    const after = hnsw.searchKNN(query, 6).find((r) => r.id === 2)!;

    // Stale: the score is NOT what a fresh computation over the mutated
    // vector would give, because the norm cached at insert time is reused.
    expect(after.score).not.toBe(cosineSimilarity([-50, 4, 5], query));
    // Stable: repeated searches keep returning the same (stale) score.
    const again = hnsw.searchKNN(query, 6).find((r) => r.id === 2)!;
    expect(again.score).toBe(after.score);
    // And the pre-mutation score was the honest one.
    expect(before.score).toBe(cosineSimilarity([3, 4, 5], query));
  });
});
